# Run updates

#- name: update
#  delegate_to: "{{ host }}"
#  raw: yum update -y


# Add a webserver

- name: install httpd
  delegate_to: "{{ host }}"
  raw: yum install httpd -y

- name: install git
  delegate_to: "{{ host }}"
  raw: yum install git -y

- name: copy files
  delegate_to: "{{ host }}"
  raw: git clone https://github.com/BlackrockDigital/startbootstrap-landing-page.git

- name: move files
  delegate_to: "{{ host }}"
  raw: cp -r startbootstrap-landing-page/. /var/www/html

- name: start service
  delegate_to: "{{ host }}"
  raw: systemctl start httpd
