---

- name: Create a started container
  lxd_container:
    name: "centos8-1"
    state: started
    source:
      type: image
      mode: pull
      server: https://images.linuxcontainers.org
      protocol: lxd
      alias: centos/8/amd64
    profiles: ["default"]
    wait_for_ipv4_addresses: true
    timeout: 600
