# Run updates

- name: apt update
  delegate_to: "testweb2"
  raw: apt update


# Add a webserver

- name: install nginx
  delegate_to: "{{ host }}"
  raw: apt install nginx -y

- name: install git
  delegate_to: "{{ host }}"
  raw: apt install git -y

#- name: copy files
#  delegate_to: "{{ host }}"
#  raw: git clone https://github.com/BlackrockDigital/startbootstrap-landing-page.git

- name: move files
  delegate_to: "{{ host }}"
  raw: cp -r startbootstrap-landing-page/. /usr/share/nginx/html
